### ISSUE TITLE
local preview feature seems to be uploading the .git folder

### ISSUE THREAD

**Issue by cedricspaceiq** [spacelift-io/spacectl#48] opened 2022-01-15 00:19 UTC
Quick question: how do I get spacectl `stack local-preview --id <stack-id>` to ignore the .git folder. Seems to be uploading that every time and it's about 70mb which is causing the upload time to take a while.

Here's a snippet from my terminal output: 
`Uploading local workspace.`
`320.00 KiB / 69.73 MiB [>`

Thanks!

**Comment by b4k3r** [comment] 2022-01-19 12:36
Hello, 

Unfortunately, I couldn't reproduce this issue. Spacelift CLI ignores `.git` directory by default. To get more context, could you provide details about:
- Version of spacectl you use
- Operating system
- The rough directory structure of your project
- What directory are you executing spacectl from

**Comment by tomasmik** [comment] 2023-08-04 09:03
Could not reproduce either, closing the issue.

**Closed by tomasmik** 2023-08-04 09:03 UTC
